Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -47,33 +47,29 @@ jobs:
       - name: Run MLflow Project and Get Run ID
         id: mlflow_run_step
         run: |
-          set -x # Mengaktifkan mode debug shell untuk melihat setiap perintah dieksekusi
+          set -x
           cd MLproject
-
+      
           echo "### Debugging MLproject Directory and Script Execution ###"
-          echo "--- Listing contents of MLproject/ with file types ---"
-          ls -al . # Menampilkan semua file (termasuk tersembunyi) dengan detail tipe dan izin
-          echo "--- Content of MLproject file (raw) ---"
-          cat MLproject || echo "MLproject file not found or cannot be read." # Mencetak isi file MLproject
-          echo "--- Attempting to run modelling.py directly ---"
-          # Jalankan modelling.py secara langsung untuk melihat output/errornya.
-          # set +e: Sementara menonaktifkan exit on error agar python error tidak langsung menghentikan shell.
+          ls -al .
+          cat MLproject || echo "MLproject file not found or cannot be read."
           set +e
           python modelling.py --data_path dataset_tempat_wisata_bali_processed.csv
-          PYTHON_DIRECT_RUN_EXIT_CODE=$? # Menangkap kode keluar dari eksekusi python langsung
-          set -e # Mengaktifkan kembali exit on error
+          PYTHON_DIRECT_RUN_EXIT_CODE=$?
+          set -e
           echo "modelling.py direct run exit code: $PYTHON_DIRECT_RUN_EXIT_CODE"
-          
-          echo "--- Attempting MLflow Run with verbose output ---"
-          # Set MLFLOW_VERBOSE=1 untuk logging yang lebih detail dari MLflow
+      
+          # MLflow Auth for DagsHub
+          export MLFLOW_TRACKING_USERNAME="mariouskono"
+          export MLFLOW_TRACKING_PASSWORD="${{ env.DAGSHUB_TOKEN }}"
+      
           MLFLOW_RUN_OUTPUT=$(MLFLOW_VERBOSE=1 mlflow run . --env-manager=local 2>&1)
-          echo "$MLFLOW_RUN_OUTPUT" # Mencetak output yang ditangkap dari mlflow run
-
-          # Ekstraksi RUN_ID (hanya akan berfungsi jika mlflow run berhasil mencetak ID)
+          echo "$MLFLOW_RUN_OUTPUT"
+      
           RUN_ID=$(echo "$MLFLOW_RUN_OUTPUT" | grep "=== Run (ID" | awk -F"'" '{print $2}')
           echo "mlflow_run_id=$RUN_ID" >> $GITHUB_OUTPUT
-        continue-on-error: true # Tetap aktifkan ini agar kita bisa melihat semua output debug meskipun ada kegagalan.
-
+        continue-on-error: true
+  
       - name: Build Docker Image from MLflow Model
         # Langkah ini hanya akan berjalan jika 'mlflow_run_id' berhasil diekstrak
         run: |
